version: "3.7"

services:
    victim:
        image: jlesage/firefox
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            - mitm

    wordpress:
        image: wordpress:4.7.0-php7.1-apache
        restart: always
        ports:
            - "9090:80"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: my_db_root_password
            WORDPRESS_DB_NAME: wordpress
        networks:
            - mitm

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my_db_root_password
            MYSQL_DATABASE: wordpress
        networks:
            - mitm

    hecker:
        privileged: true
        build: .
        volumes:
            - ./hecker:/olicyber
        sysctls:
            # Necessary for transparent mode for mitmproxy
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
